# version : "3.8"
services:
  patient-service:
    build: ./patient-service
    image: patient-service:latest
    container_name: patient-service
    ports:
      - 8080:8080
    networks:
      - internal
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://patient-service-db:5432/patient_mgmt
      - SPRING_DATASOURCE_USERNAME=athisii
      - SPRING_DATASOURCE_PASSWORD=athisii
    depends_on:
      - patient-service-db

  patient-service-db:
    image: postgres
    container_name: patient-service-db
    environment:
      - POSTGRES_DB=patient_mgmt
      - POSTGRES_USER=athisii
      - POSTGRES_PASSWORD=athisii
    ports:
      - 5432:5432
    networks:
      - internal
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

networks:
  internal:
    driver: bridge