spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://auth-service:8083
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: patience-service-route
          uri: http://patient-service:8080
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: api-docs-patient-route
          uri: http://patient-service:8080
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs

        - id: api-docs-auth-route
          uri: http://auth-service:8083
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs

auth:
  service:
    url: http://localhost:8083

server:
  port: 8443
