-- Ensure the 'patient' table exists
CREATE TABLE IF NOT EXISTS patient
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255)        NOT NULL,
    email           VARCHAR(255) UNIQUE NOT NULL,
    address         VARCHAR(255)        NOT NULL,
    phone           VARCHAR(255)        NOT NULL,
    birth_date      DATE                NOT NULL,
    registered_date DATE                NOT NULL
);

INSERT INTO patient (name, email, address, phone, birth_date, registered_date)
values ('kapesa', 'kapesa@email.com', 'Chowainu', '8974328198', '1997-07-10', now());

INSERT INTO patient (name, email, address, phone, birth_date, registered_date)
values ('mercy', 'mercy@email.com', 'Makhan Centre', '9768123465', '1980-02-11', now() + INTERVAL '10 minutes');

INSERT INTO patient (name, email, address, phone, birth_date, registered_date)
values ('athisii', 'athisii@email.com', 'Makhan Khullen', '8132789647', '1976-01-08', now() + INTERVAL '30 minutes');

INSERT INTO patient (name, email, address, phone, birth_date, registered_date)
values ('ekhe', 'ekhe@email.com', 'Makhan Khullen', '9436819704', '1994-06-15', now() + INTERVAL '2 hours');





